version: '3'
services:
   mongodb:
       image: mongo
       restart: always
       environment:
        - MONGO_INITDB_ROOT_USERNAME=admin
        - MONGO_INITDB_ROOT_PASSWORD=1234qwer
       ports:
         - "27017:27017"
       volumes:
         - $HOME/db/docker/d1/mongodata:/data/db
